export const ADD_ALL_POSTS = 'ADD_ALL_POSTS';
export const ADD_POST = 'ADD_POST';
export const REMOVE_POST = 'REMOVE_POST';

export const ADD_PENDING_POST = 'ADD_PENDING_POST';
export const REMOVE_PENDING_POST = 'ADD_PENDING_POST';

export const ADD_PENDING_COMMENT = 'ADD_PENDING_COMMENT';
export const REMOVE_PENDING_COMMENT = 'REMOVE_PENDING_COMMENT';

/*export const SET_LOADING = 'SET_LOADING';

export const SET_STATUS_SUCCESS = 'SET_STATUS_SUCCESS';
export const SET_STATUS_FAILURE = 'SET_STATUS_FAILURE';
*/
